# Railway Deployment Configuration
nixpacks.toml

[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[phases.build]
cmds = ["npm ci"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/chromium/bin/chromium"
