services:
  - type: web
    name: dvslot-api
    runtime: node
    env: node
    region: oregon
    plan: free  # Free tier: 750 hours/month
    branch: main
    rootDir: backend  # Important: Tell Render to look in backend folder
    buildCommand: npm ci && npx puppeteer browsers install chrome
    startCommand: npm start
    healthCheckPath: /health
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://mrqwzdrdbdguuaarjkwh.supabase.co
      - key: SUPABASE_SERVICE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ycXd6ZHJkYmRndXVhYXJqa3doIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDc3NTkxMiwiZXhwIjoyMDcwMzUxOTEyfQ.uRXTkQ9wBC6A90dkGWt_YfiqVZU85-WdO4myxWbQMhY
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://dvs-lot.vercel.app
      - key: SCRAPER_INTERVAL
        value: "1800000"  # 30 minutes
      - key: MAX_CONCURRENT_SCRAPERS
        value: "3"  # Conservative for free tier
      - key: RATE_LIMIT_REQUESTS
        value: "100"  # Per 15 minutes
      - key: LOG_LEVEL
        value: info
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/opt/render/.cache/puppeteer/chrome/linux-140.0.7339.82/chrome-linux64/chrome"
        
    # Auto-deploy on git push
    autoDeploy: true
    
    # Health check configuration
    healthCheckPath: /health
    
    # Resource limits for free tier
    disk:
      name: dvslot-disk
      size: 1GB
      
databases:
  # Using Supabase (PostgreSQL) - already configured
  # No additional database needed as we're using Supabase
  
# Static site for documentation (optional)
  - type: static
    name: dvslot-docs
    staticPublishPath: ./docs
    buildCommand: echo "Documentation site"
    routes:
      - type: redirect
        source: /*
        destination: https://dvs-lot.vercel.app
