import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL || 'https://your-project.supabase.co';
const supabaseAnonKey = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || 'your-anon-key';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Database Types (will be generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          updated_at: string;
        };
      };
      test_centers: {
        Row: {
          id: string;
          name: string;
          address: string;
          postcode: string;
          latitude: number;
          longitude: number;
        };
      };
      alerts: {
        Row: {
          id: string;
          user_id: string;
          test_center_id: string;
          preferred_dates: string[];
          notification_enabled: boolean;
          created_at: string;
        };
      };
      driving_test_slots: {
        Row: {
          id: string;
          test_center_id: string;
          date: string;
          time: string;
          is_available: boolean;
          price: number;
          created_at: string;
        };
      };
    };
  };
}
